[package]
name = "pc-letter"
version = "0.0.1"
entrypoint = "src/lib.typ"
authors = ["Florian Breit <florian@florian.me.uk>"]
license = "MIT"
description = "A simple letter template for personal correspondence."
repository = "https://github.com/thatfloflo/typst-pc-letter"
keywords = ["letter", "correspondence", "din5008"]
categories = ["office"]

[template]
path = "src"
entrypoint = "lib.typ"
thumbnail = "example/example.png"
